default_install_hook_types: [pre-commit, commit-msg, pre-push]
default_language_version:
    python: python3.10

ci:
    skip: [pytest-check, commit-msg-hook]
    autofix_commit_msg: |
        🚧 build: [pre-commit.ci] auto fixes from pre-commit.com hooks
    autofix_prs: true
    autoupdate_schedule: weekly
    autoupdate_commit_msg: |
        🚧 build: [pre-commit.ci] pre-commit autoupdate

repos:
-   repo: https://github.com/asottile/pyupgrade
    rev:  v3.15.2
    hooks:
    -   id: pyupgrade
        args: ["--py310-plus", "--keep-runtime-typing"]
        stages: [pre-commit]

-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
        stages: [pre-commit]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev:  v0.4.2
    hooks:
    -   id: ruff
        stages: [pre-commit]
        args:
        - --fix

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev:  v5.0.0
    hooks:
    -   id: fix-byte-order-marker
        stages: [pre-commit]
    -   id: trailing-whitespace
        stages: [pre-commit]
    -   id: end-of-file-fixer
        stages: [pre-commit]
    -   id: check-yaml
        args: ["--unsafe"]
        stages: [pre-commit]
    -   id: check-toml
        stages: [pre-commit]

-   repo: https://github.com/korawica/clishelf
    rev: v0.2.21
    hooks:
    -   id: shelf-commit-msg

#-   repo: local
#    hooks:
#    -   id: pytest-check
#        name: pytest-runner
#        stages: [pre-push]
#        types: [python]
#        entry: .venv/bin/pytest -vv
#        language: system
#        pass_filenames: false
#        always_run: true
